server:
  port:8080

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/led?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: sea123

mybatis:
  mapper-locations: classpath:mapper/*.xml

